// Builds src/styles/icons/: the Tabler icon font cut down to the icons this app
// uses. The full font is ~500 KB and has 5,000+ icons; we use a few hundred.
// Runs before every build (npm "prebuild"), so a newly used icon is always included.
//
// An icon counts as used when its name appears anywhere in src/ or index.html,
// with or without the "ti-" prefix, which also catches names kept in data
// (icon: "user") and built in templates (`ti ti-${icon}`). Names assembled from
// pieces must be listed in ALWAYS below.
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, unlinkSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PKG = join(ROOT, 'node_modules/@tabler/icons-webfont/dist')
const OUT = join(ROOT, 'src/styles/icons')
// Built from parts somewhere: `ti-chevron-${up ? 'up' : 'down'}`, `ti-player-${...}`
const ALWAYS = ['chevron-up', 'chevron-down', 'chevron-left', 'chevron-right', 'player-play', 'player-pause']

const css = readFileSync(join(PKG, 'tabler-icons.min.css'), 'utf8')
const icons = new Map() // name -> "\\ea01"
for (const m of css.matchAll(/\.ti-([a-z0-9-]+):before\{content:"(\\[0-9a-f]+)"\}/g)) icons.set(m[1], m[2])
if (icons.size < 1000) throw new Error(`Only ${icons.size} icons parsed from the Tabler CSS; its format changed`)

const files = []
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f)
    if (statSync(p).isDirectory()) { if (f !== 'icons') walk(p) } else if (/\.(tsx?|jsx?|css|html)$/.test(f)) files.push(p)
  }
}
walk(join(ROOT, 'src'))
files.push(join(ROOT, 'index.html'))

const used = new Set(ALWAYS.filter((n) => icons.has(n)))
for (const f of files) {
  for (const [t] of readFileSync(f, 'utf8').toLowerCase().matchAll(/[a-z0-9]+(?:-[a-z0-9]+)*/g)) {
    const name = t.startsWith('ti-') ? t.slice(3) : t
    if (icons.has(name)) used.add(name)
  }
}

const names = [...used].sort()
const chars = names.map((n) => String.fromCodePoint(parseInt(icons.get(n).slice(1), 16))).join('')
const font = await subsetFont(readFileSync(join(PKG, 'fonts/tabler-icons.woff2')), chars, { targetFormat: 'woff2' })

// The font is served from public/fonts under a name made from its contents, so
// the year-long cache (vercel.json) never serves an old set of icons, and
// index.html preloads it by that name
const FONTS = join(ROOT, 'public/fonts')
const fontName = `tabler-icons-${createHash('sha256').update(font).digest('hex').slice(0, 8)}.woff2`
mkdirSync(OUT, { recursive: true })
mkdirSync(FONTS, { recursive: true })
for (const f of readdirSync(FONTS)) if (/^tabler-icons-[0-9a-f]{8}\.woff2$/.test(f) && f !== fontName) unlinkSync(join(FONTS, f))
writeFileSync(join(FONTS, fontName), font)
const html = join(ROOT, 'index.html')
writeFileSync(html, readFileSync(html, 'utf8').replace(/\/fonts\/tabler-icons-[0-9a-f]{8}\.woff2/, `/fonts/${fontName}`))
writeFileSync(join(OUT, 'tabler-icons.css'), [
  `/* Generated by scripts/icons-subset.mjs from @tabler/icons-webfont: ${names.length} of ${icons.size} icons. Don't edit. */`,
  // block: icons are private-use characters, so a fallback font would show boxes
  `@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:block;src:url("/fonts/${fontName}") format("woff2")}`,
  '.ti{font-family:"tabler-icons" !important;speak:none;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}',
  ...names.map((n) => `.ti-${n}:before{content:"${icons.get(n)}"}`),
  '',
].join('\n'))
console.log(`icons-subset: ${names.length} of ${icons.size} icons, ${Math.round(font.length / 1024)} KB`)
